<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

use \dmstr\bootstrap\Tabs;
use kartik\file\FileInput;
use yii\web\JsExpression;
use kartik\select2\Select2;
$this->title = 'Cadastrar Animal';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-animal">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('animalFormSubmitted')): ?>

        <div class="alert alert-success">
            Obrigado por cadastrar o animal. A moderação analisará os dados.
        </div>

       

    <?php else: ?>

        <p>
            Se você tem alguma dúvida ou sugestão, entre em contato conosco.
        </p>

        <div class="row">
<div class="col-lg-5">
<div class="animal-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Animal',
    //'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error',
    'options' => ['enctype' => 'multipart/form-data']
    ]
    );
    ?>

    <div class="">
        

        <p>
            
            
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'animal_type_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\AnimalType::find()->all(), 'id', 'name'),
    ['prompt' => Yii::t('app', 'Selecione')]
); ?>

            <?php //echo $form->field($model, 'location')->textInput(['maxlength' => true]) ?>


        <?php
        echo '<label class="control-label">Localização</label>';
        $url = \yii\helpers\Url::to(['gmaps-list']);
        echo Select2::widget([
            'model' => $model,
            'attribute' => 'location',
            // 'name' => 'Animal[location]',
            // 'id' => 'animal-location',
            //'initValueText' => $cityDesc, // set the initial display text
            'options' => ['placeholder' => 'Procure pelo endereço...'],
            'pluginOptions' => [
                'allowClear' => true,
                'minimumInputLength' => 5,
                'language' => [
                    'errorLoading' => new JsExpression("function () { return 'Buscando resultados...'; }"),
                ],
                'ajax' => [
                    'url' => $url,
                    'dataType' => 'json',
                    //'data' => new JsExpression('function(params) { return {q:params.formatted_address}; }')
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],
                'templateResult' => new JsExpression('function(result) { return result.text; }'),
                'templateSelection' => new JsExpression('function(result) { return result.text; }'),
                //'escapeMarkup' => new JsExpression('function(result) { return result; }'),
                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                //'templateResult' => new JsExpression('function(city) { return city.text; }'),
                //'templateSelection' => new JsExpression('function (city) { return city.text; }'),
            ],
        ]);
?>
<br>


            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'extra_information')->textarea(['rows' => 6]) ?>

            
            
            <?php
        echo $form->field($model, 'photo')->widget(FileInput::classname(), [
            'options' => ['accept' => 'image/*'],
            'language' => 'pt'
        ]);
        ?>
        </p>
      
        

        
        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        
        ($model->isNewRecord ? Yii::t('app', 'Enviar') : Yii::t('app', 'Enviar')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-primary'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
        </div></div>

    <?php endif; ?>
</div>
