<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "animal_type".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \app\models\Animal[] $animals
 * @property string $aliasModel
 */
abstract class AnimalType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'animal_type';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'Tipos de Animal');
        }else{
            return Yii::t('app', 'Tipo de Animal');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nome'),
        ];
    }

    /**
     * @inheritdoc
     */
    // public function attributeHints()
    // {
    //     return array_merge(
    //         parent::attributeHints(),
    //         [
    //         'id' => Yii::t('app', 'ID'),
    //         'name' => Yii::t('app', 'Name'),
    //         ]);
    // }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnimals()
    {
        return $this->hasMany(\app\models\Animal::className(), ['animal_type_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\AnimalTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\AnimalTypeQuery(get_called_class());
    }


}
