<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\file\FileInput;
/**
* @var yii\web\View $this
* @var app\models\Animal $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="animal-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Animal',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error',
    'options' => ['enctype' => 'multipart/form-data']
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'animal_type_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\AnimalType::find()->all(), 'id', 'name'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'status_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Status::find()->all(), 'id', 'name'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
			<?= $form->field($model, 'location')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'extra_information')->textarea(['rows' => 6]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'username_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\User::find()->all(), 'id', 'name'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
			
			
            <?php
        echo $form->field($model, 'photo')->widget(FileInput::classname(), [
            'options' => ['accept' => 'image/*'],
            'language' => 'pt'
        ]);
        ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => $model->getAliasModel(),
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

