<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Yes' => 'Sim',
    'Animais' => '',
    'Animal' => '',
    'Animal Type' => 'Tipo de Animal',
    'Are you sure to delete this item?' => 'Tem certeza?',
    'Assunto' => '',
    'Atualizado Em' => '',
    'Auth Key' => '',
    'Blog' => '',
    'Blogs' => '',
    'CADASTRE AQUI' => '',
    'Cancel' => 'Cancelar',
    'Contact' => 'Contato',
    'Contacts' => 'Contatos',
    'Conteúdo' => '',
    'Copy' => 'Copiar',
    'Create' => 'Criar',
    'Criado Em' => '',
    'Criado em' => '',
    'Delete' => 'Apagar',
    'Detalhes' => '',
    'E-mail' => '',
    'Edit' => 'Editar',
    'Endereço IP' => '',
    'Enviar' => '',
    'First' => 'Primeiro',
    'Foto' => '',
    'Full list' => 'Lista completa',
    'ID' => '',
    'Informação Extra' => '',
    'Last' => 'Último',
    'Lembrar-me' => '',
    'List All' => 'Listar Todos',
    'Localização' => '',
    'Mensagem' => '',
    'Name' => 'Nome',
    'New' => 'Novo',
    'Nome' => '',
    'Permissão' => '',
    'Permissões' => '',
    'Relations' => 'Relacionamentos',
    'Reset' => 'Resetar',
    'Role' => 'Permissão',
    'Save' => 'Salvar',
    'Search' => 'Procurar',
    'Selecione' => '',
    'Select' => 'Selecione',
    'Senha' => '',
    'Status' => '',
    'Telefone' => '',
    'Tipo de Animal' => '',
    'Tipos de Animal' => '',
    'User' => 'Usuário',
    'Userr' => '',
    'Users' => 'Usuários',
    'Usuário' => '',
    'View' => 'Ver',
];
